FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci --omit=dev || npm install --omit=dev

COPY src ./src

ENV OUTPUT_DIR=/data
RUN mkdir -p /data

ENTRYPOINT ["node","src/cli.js"]
